/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   colors.h                                           :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: fmaurer <fmaurer42@posteo.de>              +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2025/03/20 22:31:00 by fmaurer           #+#    #+#             */
/*   Updated: 2025/03/21 10:07:34 by fmaurer          ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

/* All the X11 colors extracted from
 * https://en.wikipedia.org/wiki/X11_color_names */

#ifndef COLORS_H
# define COLORS_H

# define ALICE_BLUE           "f0f8ff"
# define ANTIQUE_WHITE        "faebd7"
# define AQUA                 "00ffff"
# define AQUAMARINE           "7fffd4"
# define AZURE                "f0ffff"
# define BEIGE                "f5f5dc"
# define BISQUE               "ffe4c4"
# define BLACK                "000000"
# define BLANCHED_ALMOND      "ffebcd"
# define BLUE                 "0000ff"
# define BLUE_VIOLET          "8a2be2"
# define BROWN                "a52a2a"
# define BURLYWOOD            "deb887"
# define CADET_BLUE           "5f9ea0"
# define CHARTREUSE           "7fff00"
# define CHOCOLATE            "d2691e"
# define CORAL                "ff7f50"
# define CORNFLOWER_BLUE      "6495ed"
# define CORNSILK             "fff8dc"
# define CRIMSON              "dc143c"
# define CYAN                 "00ffff"
# define DARK_BLUE            "00008b"
# define DARK_CYAN            "008b8b"
# define DARK_GOLDENROD       "b8860b"
# define DARK_GRAY            "a9a9a9"
# define DARK_GREEN           "006400"
# define DARK_KHAKI           "bdb76b"
# define DARK_MAGENTA         "8b008b"
# define DARK_OLIVE_GREEN     "556b2f"
# define DARK_ORANGE          "ff8c00"
# define DARK_ORCHID          "9932cc"
# define DARK_RED             "8b0000"
# define DARK_SALMON          "e9967a"
# define DARK_SEA_GREEN       "8fbc8f"
# define DARK_SLATE_BLUE      "483d8b"
# define DARK_SLATE_GRAY      "2f4f4f"
# define DARK_TURQUOISE       "00ced1"
# define DARK_VIOLET          "9400d3"
# define DEEP_PINK            "ff1493"
# define DEEP_SKY_BLUE        "00bfff"
# define DIM_GRAY             "696969"
# define DODGER_BLUE          "1e90ff"
# define FIREBRICK            "b22222"
# define FLORAL_WHITE         "fffaf0"
# define FOREST_GREEN         "228b22"
# define FUCHSIA              "ff00ff"
# define GAINSBORO            "dcdcdc"
# define GHOST_WHITE          "f8f8ff"
# define GOLD                 "ffd700"
# define GOLDENROD            "daa520"
# define GRAY                 "bebebe"
# define WEB_GRAY             "808080"
# define GREEN                "00ff00"
# define WEB_GREEN            "008000"
# define GREEN_YELLOW         "adff2f"
# define HONEYDEW             "f0fff0"
# define HOT_PINK             "ff69b4"
# define INDIAN_RED           "cd5c5c"
# define INDIGO               "4b0082"
# define IVORY                "fffff0"
# define KHAKI                "f0e68c"
# define LAVENDER             "e6e6fa"
# define LAVENDER_BLUSH       "fff0f5"
# define LAWN_GREEN           "7cfc00"
# define LEMON_CHIFFON        "fffacd"
# define LIGHT_BLUE           "add8e6"
# define LIGHT_CORAL          "f08080"
# define LIGHT_CYAN           "e0ffff"
# define LIGHT_GOLDENROD      "fafad2"
# define LIGHT_GRAY           "d3d3d3"
# define LIGHT_GREEN          "90ee90"
# define LIGHT_PINK           "ffb6c1"
# define LIGHT_SALMON         "ffa07a"
# define LIGHT_SEA_GREEN      "20b2aa"
# define LIGHT_SKY_BLUE       "87cefa"
# define LIGHT_SLATE_GRAY     "778899"
# define LIGHT_STEEL_BLUE     "b0c4de"
# define LIGHT_YELLOW         "ffffe0"
# define LIME                 "00ff00"
# define LIME_GREEN           "32cd32"
# define LINEN                "faf0e6"
# define MAGENTA              "ff00ff"
# define MAROON               "b03060"
# define WEB_MAROON           "800000"
# define MEDIUM_AQUAMARINE    "66cdaa"
# define MEDIUM_BLUE          "0000cd"
# define MEDIUM_ORCHID        "ba55d3"
# define MEDIUM_PURPLE        "9370db"
# define MEDIUM_SEA_GREEN     "3cb371"
# define MEDIUM_SLATE_BLUE    "7b68ee"
# define MEDIUM_SPRING_GREEN  "00fa9a"
# define MEDIUM_TURQUOISE     "48d1cc"
# define MEDIUM_VIOLET_RED    "c71585"
# define MIDNIGHT_BLUE        "191970"
# define MINT_CREAM           "f5fffa"
# define MISTY_ROSE           "ffe4e1"
# define MOCCASIN             "ffe4b5"
# define NAVAJO_WHITE         "ffdead"
# define NAVY_BLUE            "000080"
# define OLD_LACE             "fdf5e6"
# define OLIVE                "808000"
# define OLIVE_DRAB           "6b8e23"
# define ORANGE               "ffa500"
# define ORANGE_RED           "ff4500"
# define ORCHID               "da70d6"
# define PALE_GOLDENROD       "eee8aa"
# define PALE_GREEN           "98fb98"
# define PALE_TURQUOISE       "afeeee"
# define PALE_VIOLET_RED      "db7093"
# define PAPAYA_WHIP          "ffefd5"
# define PEACH_PUFF           "ffdab9"
# define PERU                 "cd853f"
# define PINK                 "ffc0cb"
# define PLUM                 "dda0dd"
# define POWDER_BLUE          "b0e0e6"
# define PURPLE               "a020f0"
# define WEB_PURPLE           "800080"
# define REBECCA_PURPLE       "663399"
# define RED                  "ff0000"
# define ROSY_BROWN           "bc8f8f"
# define ROYAL_BLUE           "4169e1"
# define SADDLE_BROWN         "8b4513"
# define SALMON               "fa8072"
# define SANDY_BROWN          "f4a460"
# define SEA_GREEN            "2e8b57"
# define SEASHELL             "fff5ee"
# define SIENNA               "a0522d"
# define SILVER               "c0c0c0"
# define SKY_BLUE             "87ceeb"
# define SLATE_BLUE           "6a5acd"
# define SLATE_GRAY           "708090"
# define SNOW                 "fffafa"
# define SPRING_GREEN         "00ff7f"
# define STEEL_BLUE           "4682b4"
# define TAN                  "d2b48c"
# define TEAL                 "008080"
# define THISTLE              "d8bfd8"
# define TOMATO               "ff6347"
# define TURQUOISE            "40e0d0"
# define VIOLET               "ee82ee"
# define WHEAT                "f5deb3"
# define WHITE                "ffffff"
# define WHITE_SMOKE          "f5f5f5"
# define YELLOW               "ffff00"
# define YELLOW_GREEN         "9acd32"

#endif
